### ISSUE TITLE
DSS7 issue - DTS Tab initialization fails if DSS7 files are previously loaded

### ISSUE THREAD

**Issue by adamkorynta** [CVWRSM/cvwrsm#178]
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-12-05 11:38:18.648
!MESSAGE
!STACK 0
java.lang.IllegalArgumentException: Catalog is empty ?
at vista.db.dss.DSSCatalogReader.readCatalog(DSSCatalogReader.java:95)
at vista.db.dss.DSSCatalogReader.(DSSCatalogReader.java:82)
at vista.db.dss.DSSUtil.createCatalogReader(DSSUtil.java:562)
at vista.db.dss.DSSGroup.getInitializedGroup(DSSGroup.java:108)
at vista.set.GroupProxy.initializeGroup(GroupProxy.java:205)
at vista.set.GroupProxy.getNumberOfDataReferences(GroupProxy.java:77)
at calsim.app.Project.setDVHashtable(Project.java:115)
at gov.ca.dwr.hecdssvue.components.DataOps.setProject(DataOps.java:524)
at gov.ca.dwr.hecdssvue.views.DTSView.createPartControl(DTSView.java:49)
at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:141)
```

The way to reproduce is to close all perspectives, reopen WRIMS GUI, loading DSS7 files in the DSS Files Compare, then switch to DTS.

The `DataOps.setProject()` method is the culprit as it seems to be inconsistent. There was a similar call removed in commit https://github.com/CentralValleyModeling/wrims/commit/428f5098dc81ae91a3ed153444120ead3d65a012 so maybe resolution of this issue is just to remove the call from the DTSView.

The issue is that internally Vista looks for a catalog file in the directory of the DSS file being opened. In DSS7 there is no catalog file (the catalog is stored in memory), which Vista sees as an error.

Found during testing of https://github.com/CentralValleyModeling/wrims/pull/176

**Comment by hxiedwr** [comment]
I guess I found the source code for CalSim jar used here. It has been a long time. I think the CalSim jar has to be modified so WRIMS doesn't use vista library. I will share the source code with RMA shortly.

**Comment by adamkorynta** [comment]
@hxiedwr - quick update. I remove dependencies onto calsimgui and moves all the DTS code from calsimgui into hecdssvue plugin. I ran into several other DSS7 issues, but now have data actually retrieving for DSS6 and DSS7 files in the DTS tab.

The current issue I am running into is with reading DSS7 files where the ending time window is filling with invalid data:
![image](https://github.com/user-attachments/assets/e3336897-5327-4603-85cb-9bad1c980741)

I'll keep you posted on what is happening and provide a resolution.

**Comment by adamkorynta** [comment]
I was able to resolve that issue with the DTS by filtering out all invalid values not just -901.0

**Comment by hxiedwr** [comment]
OK. Thank you for update.

**Comment by adamkorynta** [comment]
@hxiedwr - moving onto now an issue with MTS not working for DSS7 files. Still diagnosing

**Comment by hxiedwr** [comment]
I don't think MTS is developed in WIRMS GUI but only DTS.

**Comment by adamkorynta** [comment]
![image](https://github.com/user-attachments/assets/78db41f3-e1f7-41ed-bd40-fd69fe21fa82)

I was able to plot an MTS for DSS6. Should I hold off on any diagnosis of DSS7?

**Comment by adamkorynta** [comment]
well now MTS seems to be working just fine after restarting the application

**Comment by adamkorynta** [comment]
The following issues have been addressed:

- DTS Tab would not render if DSS7 files were loaded - fixed by moving CalSimGui code into hecdssvue plugin and removing the redundant catalog call.
- DTS Tab would not plot DSS7 with new catalog call - fixed by hand patching the time window to the first block of data.
- DTS Tab showed infinity values for data past 2003 up to 2010 for DSS7 when the file only has data up to 2003 - fixed by filtering all undefined HEC constants, not just -901.0
